name: Deploy Build to Remote Server

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: production

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '19'

      - name: Install Dependencies
        run: yarn install

      - name: Create .env
        run: |
          echo "REACT_APP_NODE_ENV=${{ secrets.REACT_APP_NODE_ENV }}" >> .env
          echo "PORT=${{ secrets.PORT }}" >> .env
          echo "REACT_APP_URL_PROD=${{ secrets.PREACT_APP_URL_PROD }}" >> .env
          echo "REACT_APP_BASE_URL_PROD=${{ secrets.REACT_APP_BASE_URL_PROD }}" >> .env
          echo "REACT_APP_GOOGLE_AUTH_URL_PROD=${{ secrets.REACT_APP_GOOGLE_AUTH_URL_PROD }}" >> .env
          echo "REACT_APP_GITHUB_AUTH_URL_PROD=${{ secrets.REACT_APP_GITHUB_AUTH_URL_PROD }}" >> .env
          echo "TSC_COMPILE_ON_ERROR=true" >> .env

      - name: Build Project
        run: yarn build --verbose

      - name: Deploy Build via SCP to pa-001 machine
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST_01 }}
          username: ${{ secrets.REMOTE_USER_01 }}
          key: ${{ secrets.REMOTE_PRIVATE_KEY }}
          port: ${{ secrets.REMOTE_PORT_01 }}
          source: "build/"
          target: "/home/quizio/helios"

      - name: Deploy Build via SCP to pa-002 machine
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST_02 }}
          username: ${{ secrets.REMOTE_USER_02 }}
          key: ${{ secrets.REMOTE_PRIVATE_KEY }}
          port: ${{ secrets.REMOTE_PORT_02 }}
          source: "build/"
          target: "/home/quizio/helios"
